// <auto-generated />
namespace CTWMasterClass_WebAppActivities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cubes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cubes));
        
        string IMigrationMetadata.Id
        {
            get { return "202007071508568_cubes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
